-- MySQL Script generated by MySQL Workbench
-- Fri Nov 12 19:09:08 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`usuaris`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuaris` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `premium` TINYINT NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `nom` VARCHAR(45) NOT NULL,
  `dataNaixement` DATE NULL,
  `sexe` VARCHAR(45) NULL,
  `pais` VARCHAR(45) NULL,
  `cpostal` VARCHAR(5) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`subscripcions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`subscripcions` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `usuariId` INT NULL,
  `dataInici` DATE NULL,
  `dataRenovacio` DATE NULL,
  `formaPagament` ENUM('targeta de crèdit', 'PayPal') NULL,
  PRIMARY KEY (`id`),
  INDEX `subscripcions_usuari_idx` (`usuariId` ASC) VISIBLE,
  CONSTRAINT `subscripcions_usuari`
    FOREIGN KEY (`usuariId`)
    REFERENCES `mydb`.`usuaris` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`targetesCredit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`targetesCredit` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `numTargeta` VARCHAR(45) NULL,
  `usuariId` INT NULL,
  `mes` VARCHAR(2) NULL,
  `any` VARCHAR(2) NULL,
  `ccv` VARCHAR(3) NULL,
  PRIMARY KEY (`id`),
  INDEX `targetes_usuari_idx` (`usuariId` ASC) VISIBLE,
  CONSTRAINT `targetes_usuari`
    FOREIGN KEY (`usuariId`)
    REFERENCES `mydb`.`usuaris` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pagaments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pagaments` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `usuariId` INT NULL,
  `data` DATE NULL,
  `numOrdre` INT NULL,
  `total` FLOAT NULL,
  PRIMARY KEY (`id`),
  INDEX `pagaments_usuari_idx` (`usuariId` ASC) VISIBLE,
  CONSTRAINT `pagaments_usuari`
    FOREIGN KEY (`usuariId`)
    REFERENCES `mydb`.`usuaris` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`payPals`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`payPals` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `usuariId` INT NULL,
  `nomPaypal` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `paypals_usuari_idx` (`usuariId` ASC) VISIBLE,
  CONSTRAINT `paypals_usuari`
    FOREIGN KEY (`usuariId`)
    REFERENCES `mydb`.`usuaris` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`playlists`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`playlists` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `usuariId` INT NULL,
  `titol` VARCHAR(45) NULL,
  `numCancons` INT NULL,
  `dataCreacio` DATE NULL,
  `eliminada` TINYINT NULL,
  `dataEliminacio` DATE NULL,
  PRIMARY KEY (`id`),
  INDEX `playlists_usuari_idx` (`usuariId` ASC) VISIBLE,
  CONSTRAINT `playlists_usuari`
    FOREIGN KEY (`usuariId`)
    REFERENCES `mydb`.`usuaris` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`artistes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`artistes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NULL,
  `imatge` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`albums`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`albums` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `artistaId` INT NULL,
  `titol` VARCHAR(45) NULL,
  `anyPublicacio` INT NULL,
  `imatgePortada` VARCHAR(255) NULL,
  PRIMARY KEY (`id`),
  INDEX `albums_artista_idx` (`artistaId` ASC) VISIBLE,
  CONSTRAINT `albums_artista`
    FOREIGN KEY (`artistaId`)
    REFERENCES `mydb`.`artistes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`seguidors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`seguidors` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `aritstaId` INT NULL,
  `usuariId` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `seguidors_artista_idx` (`aritstaId` ASC) VISIBLE,
  INDEX `seguidors_usuari_idx` (`usuariId` ASC) VISIBLE,
  CONSTRAINT `seguidors_artista`
    FOREIGN KEY (`aritstaId`)
    REFERENCES `mydb`.`artistes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `seguidors_usuari`
    FOREIGN KEY (`usuariId`)
    REFERENCES `mydb`.`usuaris` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`artistesRelacionats`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`artistesRelacionats` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `artistaId` INT NULL,
  `artistaRelacionatId` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `artistesR_artista_idx` (`artistaId` ASC) VISIBLE,
  INDEX `artistesR_artistaR_idx` (`artistaRelacionatId` ASC) VISIBLE,
  CONSTRAINT `artistesR_artista`
    FOREIGN KEY (`artistaId`)
    REFERENCES `mydb`.`artistes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `artistesR_artistaR`
    FOREIGN KEY (`artistaRelacionatId`)
    REFERENCES `mydb`.`artistes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cancons`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cancons` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `titol` VARCHAR(45) NULL,
  `durada` FLOAT NULL,
  `numReproduccions` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`canconsAlbum`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`canconsAlbum` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `albumId` INT NULL,
  `cancoId` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `canconsA_album_idx` (`albumId` ASC) VISIBLE,
  INDEX `canconsA_canco_idx` (`cancoId` ASC) VISIBLE,
  CONSTRAINT `canconsA_album`
    FOREIGN KEY (`albumId`)
    REFERENCES `mydb`.`albums` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `canconsA_canco`
    FOREIGN KEY (`cancoId`)
    REFERENCES `mydb`.`cancons` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`canconsPlaylist`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`canconsPlaylist` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `playlistId` INT NULL,
  `cancoId` INT NULL,
  `usuariId` INT NULL,
  `dataAfegida` DATE NULL,
  PRIMARY KEY (`id`),
  INDEX `canconsP_plalist_idx` (`playlistId` ASC) VISIBLE,
  INDEX `canconsP_usuari_idx` (`usuariId` ASC) VISIBLE,
  CONSTRAINT `canconsP_plalist`
    FOREIGN KEY (`playlistId`)
    REFERENCES `mydb`.`playlists` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `canconsP_canco`
    FOREIGN KEY (`cancoId`)
    REFERENCES `mydb`.`cancons` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `canconsP_usuari`
    FOREIGN KEY (`usuariId`)
    REFERENCES `mydb`.`usuaris` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`albumsFavorits`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`albumsFavorits` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `albumId` INT NULL,
  `usuariId` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `albumsF_album_idx` (`albumId` ASC) VISIBLE,
  INDEX `albumsF_usuari_idx` (`usuariId` ASC) VISIBLE,
  CONSTRAINT `albumsF_album`
    FOREIGN KEY (`albumId`)
    REFERENCES `mydb`.`albums` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `albumsF_usuari`
    FOREIGN KEY (`usuariId`)
    REFERENCES `mydb`.`usuaris` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`canconsFavorites`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`canconsFavorites` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cancoId` INT NULL,
  `usuariId` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `canconsF_canco_idx` (`cancoId` ASC) VISIBLE,
  INDEX `canconsF_usuari_idx` (`usuariId` ASC) VISIBLE,
  CONSTRAINT `canconsF_canco`
    FOREIGN KEY (`cancoId`)
    REFERENCES `mydb`.`cancons` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `canconsF_usuari`
    FOREIGN KEY (`usuariId`)
    REFERENCES `mydb`.`usuaris` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
