-- MySQL Script generated by MySQL Workbench
-- Tue Nov  9 18:41:23 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`usuaris`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuaris` (
  `id` INT NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `nom` VARCHAR(45) NOT NULL,
  `dataNaixement` DATE NULL,
  `sexe` VARCHAR(15) NULL,
  `cpostal` VARCHAR(5) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`videos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`videos` (
  `id` INT NOT NULL,
  `titol` VARCHAR(150) NULL,
  `descripcio` VARCHAR(250) NULL,
  `grandaria` INT NULL,
  `nomArxiu` VARCHAR(150) NULL,
  `durada` FLOAT NULL,
  `thumbnail` VARCHAR(150) NULL,
  `likes` INT NULL,
  `dislikes` INT NULL,
  `estat` ENUM('públic','ocult','privat') NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`publicacions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`publicacions` (
  `id` INT NOT NULL,
  `usuariId` INT NOT NULL,
  `videoId` INT NOT NULL,
  `data` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `p_usuari_idx` (`usuariId` ASC) VISIBLE,
  INDEX `p_video_idx` (`videoId` ASC) VISIBLE,
  CONSTRAINT `p_usuari`
    FOREIGN KEY (`usuariId`)
    REFERENCES `mydb`.`usuaris` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `p_video`
    FOREIGN KEY (`videoId`)
    REFERENCES `mydb`.`videos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`etiquetes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`etiquetes` (
  `id` INT NOT NULL,
  `nom` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `mydb`.`etiquetat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`etiquetat` (
  `id` INT NOT NULL,
  `videoId` INT NOT NULL,
  `etiquetaId` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `etiquetat_video_idx` (`videoId` ASC) VISIBLE,
  INDEX `etiquetat_etiqueta_idx` (`etiquetaId` ASC) VISIBLE,
  CONSTRAINT `etiquetat_video`
    FOREIGN KEY (`videoId`)
    REFERENCES `mydb`.`videos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `etiquetat_etiqueta`
    FOREIGN KEY (`etiquetaId`)
    REFERENCES `mydb`.`etiquetes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`canals`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`canals` (
  `id` INT NOT NULL,
  `usuariId` INT NULL,
  `nom` VARCHAR(150) NULL,
  `descripcio` VARCHAR(255) NULL,
  `dataCreacio` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `canals_usuari_idx` (`usuariId` ASC) VISIBLE,
  CONSTRAINT `canals_usuari`
    FOREIGN KEY (`usuariId`)
    REFERENCES `mydb`.`usuaris` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`suscripcions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`suscripcions` (
  `id` INT NOT NULL,
  `usuariId` INT NOT NULL,
  `canalId` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `suscripcions_usuari_idx` (`usuariId` ASC) VISIBLE,
  INDEX `suscripcions_canal_idx` (`canalId` ASC) VISIBLE,
  CONSTRAINT `suscripcions_usuari`
    FOREIGN KEY (`usuariId`)
    REFERENCES `mydb`.`usuaris` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `suscripcions_canal`
    FOREIGN KEY (`canalId`)
    REFERENCES `mydb`.`canals` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`valoracions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`valoracions` (
  `id` INT NOT NULL,
  `usuariId` INT NOT NULL,
  `videoId` INT NOT NULL,
  `like` TINYINT NOT NULL,
  `data` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `valoracions_usuari_idx` (`usuariId` ASC) VISIBLE,
  INDEX `valoracions_video_idx` (`videoId` ASC) VISIBLE,
  CONSTRAINT `valoracions_usuari`
    FOREIGN KEY (`usuariId`)
    REFERENCES `mydb`.`usuaris` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `valoracions_video`
    FOREIGN KEY (`videoId`)
    REFERENCES `mydb`.`videos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`playlists`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`playlists` (
  `id` INT NOT NULL,
  `usuariId` INT NOT NULL,
  `videoId` INT NOT NULL,
  `dataCreacio` TIMESTAMP NULL,
  `estat` ENUM('pública', 'privada') NULL,
  PRIMARY KEY (`id`),
  INDEX `playlists_usuari_idx` (`usuariId` ASC) VISIBLE,
  INDEX `playlists_video_idx` (`videoId` ASC) VISIBLE,
  CONSTRAINT `playlists_usuari`
    FOREIGN KEY (`usuariId`)
    REFERENCES `mydb`.`usuaris` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `playlists_video`
    FOREIGN KEY (`videoId`)
    REFERENCES `mydb`.`videos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`comentaris`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`comentaris` (
  `id` INT NOT NULL,
  `usuariId` INT NOT NULL,
  `videoId` INT NOT NULL,
  `dataCreacio` TIMESTAMP NULL,
  `comentari` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `comentaris_usuari_idx` (`usuariId` ASC) VISIBLE,
  INDEX `comentaris_video_idx` (`videoId` ASC) VISIBLE,
  CONSTRAINT `comentaris_usuari`
    FOREIGN KEY (`usuariId`)
    REFERENCES `mydb`.`usuaris` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `comentaris_video`
    FOREIGN KEY (`videoId`)
    REFERENCES `mydb`.`videos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`valoracions_comentaris`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`valoracions_comentaris` (
  `id` INT NOT NULL,
  `usuariId` INT NOT NULL,
  `comentariId` INT NOT NULL,
  `like` TINYINT NOT NULL,
  `data` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `valoracions_c_comentari_idx` (`comentariId` ASC) VISIBLE,
  INDEX `valoracions_c_usuari_idx` (`usuariId` ASC) VISIBLE,
  CONSTRAINT `valoracions_c_comentari`
    FOREIGN KEY (`comentariId`)
    REFERENCES `mydb`.`comentaris` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `valoracions_c_usuari`
    FOREIGN KEY (`usuariId`)
    REFERENCES `mydb`.`usuaris` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
